# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ToDoAppForRealm' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'RealmSwift', '~> 3.0.0'

  target 'ToDoAppForRealmTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ToDoAppForRealmUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
